baseURL = "https://compassionate-yalow-e93930.netlify.app/"
# baseURL = "http://www.alessandroalessio.net/"
title = "Alessandro Alessio - Siti Web e Software Alessandria"
theme = "typewriter"

languageCode = "it-it"
DefaultContentLanguage = "it"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "Sono un programmatore nerd di Alessandria con tante passioni: viaggi, videogames, fantacalcio. Li racchiudo tutti qui."
  keywords = "programmatore alessandria, siti web alessandria, creazione siti alessandria, fantacalcio alessandria"
  author = "Alessandro Alessio"
  github = "https://github.com/alessandroalessio"
  facebook = "https://www.facebook.com/a.alessio86"
  og_image = "/images/og.png"
  sitename = "Alessandro Alessio"
  twitter = "@AAlessio86"
  telegram = "https://t.me/alessandro_alessio"
  email = "info@alessandroalessio.net"
  privacyOwner = "Alessandro Alessio"
  privacyEmail = "info@a2area.it"
  privacyURL = "www.alessandroalessio.net"
  privacyHeadquarterAddress = "Via U. De Foro 1, Alessandria (AL)"
  privacyPhone = "371 4385203"
  podcastspotifyurl = ""
  podcastitunesurl = "https://podcasts.apple.com/it/podcast/i-consigli-di-un-pirla/id1529085612"
  podcastspreakerurl = "https://www.spreaker.com/show/i-consigli-di-un-pirla"
  podcastcastboxurl = ""

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"

  [[menu.main]]
    identifier = "podcast"
    name = "Podcast"
    url = "/podcast/"